# Generated by Django 3.1.5 on 2021-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210119_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('seller', 'Seller'), ('customer', 'Customer'), ('delivery', 'Delivery')], default=1, max_length=10),
        ),
    ]
