# Generated by Django 3.1.5 on 2021-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210120_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Owner'), ('2', 'Seller'), ('3', 'Customer'), ('4', 'Delivery')], default=1, max_length=10),
        ),
    ]
