# Generated by Django 3.1.5 on 2021-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='X, SM, L', max_length=100),
        ),
    ]
