# Generated by Django 3.1.5 on 2021-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Owner'), ('2', 'Seller'), ('3', 'Customer'), ('4', 'Delivery')], default='1', max_length=10),
        ),
    ]
