# Generated by Django 3.1.5 on 2021-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_seller_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='added_by',
            field=models.CharField(max_length=200),
        ),
    ]
