# Generated by Django 3.1.5 on 2021-02-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210218_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='service_provide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.service'),
        ),
    ]
